import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateBairrosRegionaisEColunasNormalizacao1789500000000 implements MigrationInterface {
  name = 'CreateBairrosRegionaisEColunasNormalizacao1789500000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "bairros_regionais" ("id" SERIAL NOT NULL, "bairro" text NOT NULL, "regional" text NOT NULL, "territorio" text NOT NULL, CONSTRAINT "UQ_bairros_regionais_bairro" UNIQUE ("bairro"), CONSTRAINT "PK_bairros_regionais" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `INSERT INTO "bairros_regionais" ("bairro", "regional", "territorio") VALUES
      ('AARÃO REIS', 'NORTE', 'N4'),
      ('ACABA MUNDO', 'CENTRO-SUL', 'CS3'),
      ('ACAIACA', 'NORDESTE', 'NE1'),
      ('ADEMAR MALDONADO', 'BARREIRO', 'B2'),
      ('AEROPORTO', 'PAMPULHA', 'P3'),
      ('ALPES', 'OESTE', 'O3'),
      ('ALTA TENSÃO', 'BARREIRO', 'B1'),
      ('ALTA TENSÃO I', 'BARREIRO', 'B1'),
      ('ALTO BARROCA', 'OESTE', 'O1'),
      ('ALTO CAIÇARAS', 'NOROESTE', 'NO2'),
      ('ALTO DAS ANTENAS', 'BARREIRO', 'B4'),
      ('ALTO DOS PINHEIROS', 'NOROESTE', 'NO4'),
      ('ALTO VERA CRUZ', 'LESTE', 'L4'),
      ('ALÍPIO DE MELO', 'PAMPULHA', 'P4'),
      ('AMBROSINA', 'OESTE', 'O2'),
      ('ANCHIETA', 'CENTRO-SUL', 'CS2'),
      ('ANDIROBA', 'NORDESTE', 'NE3'),
      ('ANTÔNIO RIBEIRO DE ABREU', 'NORDESTE', 'NE1'),
      ('APARECIDA', 'NOROESTE', 'NO1'),
      ('APARECIDA SÉTIMA SEÇÃO', 'NOROESTE', 'NO1'),
      ('APOLÔNIA', 'VENDA NOVA', 'VN4'),
      ('ARAGUAIA', 'BARREIRO', 'B4'),
      ('BACURAU', 'NORTE', 'N3'),
      ('BAIRRO DAS INDÚSTRIAS I', 'BARREIRO', 'B1'),
      ('BAIRRO DAS INDÚSTRIAS II', 'OESTE', 'O2'),
      ('BAIRRO NOVO DAS INDÚSTRIAS', 'BARREIRO', 'B1'),
      ('BALEIA', 'LESTE', 'L4'),
      ('BANDEIRANTES', 'PAMPULHA', 'P2'),
      ('BARREIRO', 'BARREIRO', 'B2'),
      ('BARRO PRETO', 'CENTRO-SUL', 'CS1'),
      ('BARROCA', 'OESTE', 'O1'),
      ('BARÃO HOMEM DE MELO I', 'OESTE', 'O3'),
      ('BARÃO HOMEM DE MELO III', 'OESTE', 'O3'),
      ('BARÃO HOMEM DE MELO IV', 'OESTE', 'O3'),
      ('BEIJA FLOR', 'NORDESTE', 'NE1'),
      ('BEIRA-LINHA', 'NORDESTE', 'NE1'),
      ('BELA VITÓRIA', 'NORDESTE', 'NE2'),
      ('BELMONTE', 'NORDESTE', 'NE1'),
      ('BELVEDERE', 'CENTRO-SUL', 'CS2'),
      ('BELÉM', 'LESTE', 'L3'),
      ('BERNADETE', 'BARREIRO', 'B1'),
      ('BETÂNIA', 'OESTE', 'O4'),
      ('BIQUINHAS', 'NORTE', 'N3'),
      ('BISPO DE MAURA', 'PAMPULHA', 'P1'),
      ('BOA ESPERANÇA', 'NORDESTE', 'NE1'),
      ('BOA UNIÃO I', 'NORTE', 'N4'),
      ('BOA UNIÃO II', 'NORTE', 'N4'),
      ('BOA VIAGEM', 'CENTRO-SUL', 'CS1'),
      ('BOA VISTA', 'LESTE', 'L1'),
      ('BOM JESUS', 'NOROESTE', 'NO1'),
      ('BONFIM', 'NOROESTE', 'NO1'),
      ('BONSUCESSO', 'BARREIRO', 'B1'),
      ('BRASIL INDUSTRIAL', 'BARREIRO', 'B4'),
      ('BRAÚNAS', 'PAMPULHA', 'P1'),
      ('BURITIS', 'OESTE', 'O5'),
      ('CABANA DO PAI TOMÁS', 'OESTE', 'O2'),
      ('CACHOEIRINHA', 'NORDESTE', 'NE4'),
      ('CAETANO FURQUIM', 'LESTE', 'L1'),
      ('CAIÇARA-ADELAIDE', 'NOROESTE', 'NO2'),
      ('CAIÇARAS', 'NOROESTE', 'NO2'),
      ('CALAFATE', 'OESTE', 'O1'),
      ('CALIFÓRNIA', 'NOROESTE', 'NO3'),
      ('CAMARGOS', 'OESTE', 'O2'),
      ('CAMPO ALEGRE', 'NORTE', 'N3'),
      ('CAMPONESA I', 'LESTE', 'L1'),
      ('CAMPONESA III', 'LESTE', 'L1'),
      ('CAMPUS UFMG', 'PAMPULHA', 'P3'),
      ('CANADÁ', 'NORDESTE', 'NE4'),
      ('CANAÃ', 'VENDA NOVA', 'VN1'),
      ('CANDELÁRIA', 'VENDA NOVA', 'VN3'),
      ('CAPITÃO EDUARDO', 'NORDESTE', 'NE1'),
      ('CARDOSO', 'BARREIRO', 'B4'),
      ('CARLOS PRATES', 'NOROESTE', 'NO4'),
      ('CARMO', 'CENTRO-SUL', 'CS2'),
      ('CASA BRANCA', 'LESTE', 'L1'),
      ('CASTANHEIRA', 'BARREIRO', 'B5'),
      ('CASTELO', 'PAMPULHA', 'P2'),
      ('CDI JATOBÁ', 'BARREIRO', 'B5'),
      ('CENTRO', 'CENTRO-SUL', 'CS1'),
      ('CENÁCULO', 'VENDA NOVA', 'VN1'),
      ('CHÁCARA LEONINA', 'OESTE', 'O3'),
      ('CIDADE JARDIM', 'CENTRO-SUL', 'CS4'),
      ('CIDADE JARDIM TAQUARIL', 'LESTE', 'L4'),
      ('CIDADE NOVA', 'NORDESTE', 'NE5'),
      ('CINQÜENTENÁRIO', 'OESTE', 'O4'),
      ('COLÉGIO BATISTA', 'NORDESTE', 'NE4'),
      ('COMITECO', 'CENTRO-SUL', 'CS2'),
      ('CONCÓRDIA', 'NORDESTE', 'NE4'),
      ('CONFISCO', 'PAMPULHA', 'P4'),
      ('CONJUNTO BONSUCESSO', 'BARREIRO', 'B1'),
      ('CONJUNTO CALIFÓRNIA I', 'NOROESTE', 'NO3'),
      ('CONJUNTO CALIFÓRNIA II', 'NOROESTE', 'NO3'),
      ('CONJUNTO CAPITÃO EDUARDO', 'NORDESTE', 'NE1'),
      ('CONJUNTO CELSO MACHADO', 'PAMPULHA', 'P4'),
      ('CONJUNTO FLORAMAR', 'NORTE', 'N2'),
      ('CONJUNTO JARDIM FILADÉLFIA', 'NOROESTE', 'NO3'),
      ('CONJUNTO JATOBÁ', 'BARREIRO', 'B5'),
      ('CONJUNTO LAGOA', 'PAMPULHA', 'P2'),
      ('CONJUNTO MINASCAIXA', 'VENDA NOVA', 'VN1'),
      ('CONJUNTO NOVO DOM BOSCO', 'NOROESTE', 'NO3'),
      ('CONJUNTO PAULO VI', 'NORDESTE', 'NE1'),
      ('CONJUNTO PROVIDÊNCIA', 'NORTE', 'N4'),
      ('CONJUNTO SANTA MARIA', 'CENTRO-SUL', 'CS5'),
      ('CONJUNTO SERRA VERDE', 'VENDA NOVA', 'VN1'),
      ('CONJUNTO SÃO FRANCISCO DE ASSIS', 'PAMPULHA', 'P1'),
      ('CONJUNTO TAQUARIL', 'LESTE', 'L4'),
      ('COPACABANA', 'VENDA NOVA', 'VN4'),
      ('COQUEIROS', 'NOROESTE', 'NO3'),
      ('CORAÇÃO DE JESUS', 'CENTRO-SUL', 'CS4'),
      ('CORAÇÃO EUCARÍSTICO', 'NOROESTE', 'NO4'),
      ('CORUMBIARA', 'BARREIRO', 'B4'),
      ('CRUZEIRO', 'CENTRO-SUL', 'CS2'),
      ('CUSTODINHA', 'OESTE', 'O2'),
      ('CÉU AZUL', 'VENDA NOVA', 'VN4'),
      ('CÔNEGO PINHEIRO', 'LESTE', 'L3'),
      ('CÔNEGO PINHEIRO A', 'LESTE', 'L3'),
      ('DELTA', 'NOROESTE', 'NO4'),
      ('DIAMANTE', 'BARREIRO', 'B2'),
      ('DISTRITO INDUSTRIAL DO JATOBÁ', 'BARREIRO', 'B5'),
      ('DOM BOSCO', 'NOROESTE', 'NO3'),
      ('DOM CABRAL', 'NOROESTE', 'NO4'),
      ('DOM JOAQUIM', 'NORDESTE', 'NE3'),
      ('DOM SILVÉRIO', 'NORDESTE', 'NE1'),
      ('DONA CLARA', 'PAMPULHA', 'P3'),
      ('ENGENHO NOGUEIRA', 'PAMPULHA', 'P2'),
      ('ERMELINDA', 'NOROESTE', 'NO1'),
      ('ERNESTO DO NASCIMENTO', 'BARREIRO', 'B5'),
      ('ESPERANÇA', 'BARREIRO', 'B4'),
      ('ESPLANADA', 'LESTE', 'L3'),
      ('ESTORIL', 'OESTE', 'O5'),
      ('ESTRELA', 'CENTRO-SUL', 'CS5'),
      ('ESTRELA DO ORIENTE', 'OESTE', 'O4'),
      ('ETELVINA CARNEIRO', 'NORTE', 'N1'),
      ('EUROPA', 'VENDA NOVA', 'VN1'),
      ('EYMARD', 'NORDESTE', 'NE3'),
      ('FAZENDINHA', 'CENTRO-SUL', 'CS3'),
      ('FERNÃO DIAS', 'NORDESTE', 'NE3'),
      ('FLAMENGO', 'VENDA NOVA', 'VN4'),
      ('FLORAMAR', 'NORTE', 'N3'),
      ('FLORESTA', 'CENTRO-SUL', 'CS1'),
      ('FLÁVIO DE OLIVEIRA', 'BARREIRO', 'B4'),
      ('FLÁVIO MARQUES LISBOA', 'BARREIRO', 'B4'),
      ('FREI LEOPOLDO', 'NORTE', 'N1'),
      ('FUNCIONÁRIOS', 'CENTRO-SUL', 'CS1'),
      ('GAMELEIRA', 'OESTE', 'O2'),
      ('GARÇAS', 'PAMPULHA', 'P1'),
      ('GLÓRIA', 'NOROESTE', 'NO3'),
      ('GOIÂNIA', 'NORDESTE', 'NE2'),
      ('GRAJAÚ', 'OESTE', 'O1'),
      ('GRANJA DE FREITAS', 'LESTE', 'L4'),
      ('GRANJA WERNECK', 'NORTE', 'N2'),
      ('GRAÇA', 'NORDESTE', 'NE5'),
      ('GROTA', 'LESTE', 'L1'),
      ('GROTINHA', 'NORDESTE', 'NE1'),
      ('GUANABARA', 'NORDESTE', 'NE2'),
      ('GUARANI', 'NORTE', 'N4'),
      ('GUARATÃ', 'OESTE', 'O2'),
      ('GUTIERREZ', 'OESTE', 'O1'),
      ('HAVAÍ', 'OESTE', 'O4'),
      ('HELIÓPOLIS', 'NORTE', 'N3'),
      ('HORTO', 'LESTE', 'L2'),
      ('HORTO FLORESTAL', 'LESTE', 'L2'),
      ('IMBAÚBAS', 'OESTE', 'O2'),
      ('INCONFIDÊNCIA', 'PAMPULHA', 'P4'),
      ('INDAIÁ', 'PAMPULHA', 'P3'),
      ('INDEPENDÊNCIA', 'BARREIRO', 'B5'),
      ('IPIRANGA', 'NORDESTE', 'NE5'),
      ('IPÊ', 'NORDESTE', 'NE3'),
      ('ITAIPU', 'BARREIRO', 'B3'),
      ('ITAPOÃ', 'PAMPULHA', 'P1'),
      ('ITATIAIA', 'PAMPULHA', 'P4'),
      ('JAQUELINE', 'NORTE', 'N1'),
      ('JARAGUÁ', 'PAMPULHA', 'P3'),
      ('JARDIM ALVORADA', 'PAMPULHA', 'P4'),
      ('JARDIM AMÉRICA', 'OESTE', 'O1'),
      ('JARDIM ATLÂNTICO', 'PAMPULHA', 'P1'),
      ('JARDIM DO VALE', 'BARREIRO', 'B5'),
      ('JARDIM DOS COMERCIÁRIOS', 'VENDA NOVA', 'VN2'),
      ('JARDIM FELICIDADE', 'NORTE', 'N2'),
      ('JARDIM GUANABARA', 'NORTE', 'N3'),
      ('JARDIM LEBLON', 'VENDA NOVA', 'VN4'),
      ('JARDIM MONTANHÊS', 'NOROESTE', 'NO2'),
      ('JARDIM SÃO JOSÉ', 'PAMPULHA', 'P4'),
      ('JARDIM VITÓRIA', 'NORDESTE', 'NE2'),
      ('JARDINÓPOLIS', 'OESTE', 'O2'),
      ('JATOBÁ', 'BARREIRO', 'B3'),
      ('JONAS VEIGA', 'LESTE', 'L3'),
      ('JOÃO ALFREDO', 'LESTE', 'L2'),
      ('JOÃO PAULO II', 'BARREIRO', 'B2'),
      ('JOÃO PINHEIRO', 'NOROESTE', 'NO4'),
      ('JULIANA', 'NORTE', 'N1'),
      ('LAGOA', 'VENDA NOVA', 'VN4'),
      ('LAGOA DA PAMPULHA', 'PAMPULHA', 'P2'),
      ('LAGOINHA', 'NOROESTE', 'NO1'),
      ('LAGOINHA LEBLON', 'VENDA NOVA', 'VN4'),
      ('LAJEDO', 'NORTE', 'N2'),
      ('LARANJEIRAS', 'VENDA NOVA', 'VN1'),
      ('LEONINA', 'OESTE', 'O3'),
      ('LETÍCIA', 'VENDA NOVA', 'VN3'),
      ('LIBERDADE', 'PAMPULHA', 'P3'),
      ('LINDÉIA', 'BARREIRO', 'B3'),
      ('LORENA', 'NOROESTE', 'NO4'),
      ('LOURDES', 'CENTRO-SUL', 'CS1'),
      ('LUXEMBURGO', 'CENTRO-SUL', 'CS4'),
      ('MADRE GERTRUDES', 'OESTE', 'O2'),
      ('MADRI', 'NORTE', 'N1'),
      ('MALA E CUIA', 'CENTRO-SUL', 'CS5'),
      ('MANACÁS', 'PAMPULHA', 'P4'),
      ('MANGABEIRAS', 'CENTRO-SUL', 'CS2'),
      ('MANGUEIRAS', 'BARREIRO', 'B5'),
      ('MANTIQUEIRA', 'VENDA NOVA', 'VN2'),
      ('MARAJÓ', 'OESTE', 'O4'),
      ('MARAVILHA', 'OESTE', 'O2'),
      ('MARIA GORETTI', 'NORDESTE', 'NE3'),
      ('MARIA HELENA', 'VENDA NOVA', 'VN2'),
      ('MARIA TERESA', 'NORTE', 'N2'),
      ('MARIA VIRGÍNIA', 'NORDESTE', 'NE4'),
      ('MARIANO DE ABREU', 'LESTE', 'L1'),
      ('MARIETA I', 'BARREIRO', 'B5'),
      ('MARIETA II', 'BARREIRO', 'B3'),
      ('MARILÂNDIA', 'BARREIRO', 'B3'),
      ('MARIQUINHAS', 'NORTE', 'N1'),
      ('MARMITEIROS', 'NOROESTE', 'NO4'),
      ('MARÇOLA', 'CENTRO-SUL', 'CS3'),
      ('MILIONÁRIOS', 'BARREIRO', 'B1'),
      ('MINAS BRASIL', 'NOROESTE', 'NO4'),
      ('MINASCAIXA', 'VENDA NOVA', 'VN1'),
      ('MINASLÂNDIA', 'NORTE', 'N4'),
      ('MINEIRÃO', 'BARREIRO', 'B5'),
      ('MIRAMAR', 'BARREIRO', 'B4'),
      ('MIRANTE', 'NORTE', 'N2'),
      ('MIRTES', 'NORDESTE', 'NE2'),
      ('MONSENHOR MESSIAS', 'NOROESTE', 'NO2'),
      ('MONTE AZUL', 'NORTE', 'N2'),
      ('MONTE SÃO JOSÉ', 'CENTRO-SUL', 'CS5'),
      ('MORRO DOS MACACOS', 'NORDESTE', 'NE2'),
      ('NAZARÉ', 'NORDESTE', 'NE1'),
      ('NOSSA SENHORA DA APARECIDA', 'CENTRO-SUL', 'CS3'),
      ('NOSSA SENHORA DA CONCEIÇÃO', 'CENTRO-SUL', 'CS3'),
      ('NOSSA SENHORA DE FÁTIMA', 'CENTRO-SUL', 'CS3'),
      ('NOSSA SENHORA DO ROSÁRIO', 'CENTRO-SUL', 'CS3'),
      ('NOVA AMÉRICA', 'VENDA NOVA', 'VN2'),
      ('NOVA CACHOEIRINHA', 'NOROESTE', 'NO1'),
      ('NOVA CINTRA', 'OESTE', 'O2'),
      ('NOVA ESPERANÇA', 'NOROESTE', 'NO1'),
      ('NOVA FLORESTA', 'NORDESTE', 'NE5'),
      ('NOVA GAMELEIRA', 'OESTE', 'O2'),
      ('NOVA GRANADA', 'OESTE', 'O1'),
      ('NOVA PAMPULHA', 'PAMPULHA', 'P1'),
      ('NOVA SUISSA', 'OESTE', 'O1'),
      ('NOVA VISTA', 'LESTE', 'L1'),
      ('NOVO AARÃO REIS', 'NORTE', 'N2'),
      ('NOVO GLÓRIA', 'NOROESTE', 'NO3'),
      ('NOVO OURO PRETO', 'PAMPULHA', 'P2'),
      ('NOVO SANTA CECÍLIA', 'BARREIRO', 'B4'),
      ('NOVO SÃO LUCAS', 'CENTRO-SUL', 'CS2'),
      ('NOVO TUPI', 'NORTE', 'N2'),
      ('OESTE', 'OESTE', 'O2'),
      ('OLARIA', 'BARREIRO', 'B5'),
      ('OLHOS D''ÁGUA', 'OESTE', 'O5'),
      ('OURO MINAS', 'NORDESTE', 'NE1'),
      ('OURO PRETO', 'PAMPULHA', 'P2'),
      ('PADRE EUSTÁQUIO', 'NOROESTE', 'NO4'),
      ('PALMARES', 'NORDESTE', 'NE5'),
      ('PALMEIRAS', 'OESTE', 'O4'),
      ('PANTANAL', 'OESTE', 'O3'),
      ('PAQUETÁ', 'PAMPULHA', 'P2'),
      ('PARAÍSO', 'LESTE', 'L3'),
      ('PARQUE SÃO JOSÉ', 'OESTE', 'O4'),
      ('PARQUE SÃO PEDRO', 'VENDA NOVA', 'VN1'),
      ('PAULO VI', 'NORDESTE', 'NE1'),
      ('PEDREIRA PRADO LOPES', 'NOROESTE', 'NO1'),
      ('PENHA', 'NORDESTE', 'NE3'),
      ('PETRÓPOLIS', 'BARREIRO', 'B5'),
      ('PILAR', 'BARREIRO', 'B1'),
      ('PINDORAMA', 'NOROESTE', 'NO3'),
      ('PINDURA SAIA', 'CENTRO-SUL', 'CS3'),
      ('PIRAJÁ', 'NORDESTE', 'NE3'),
      ('PIRATININGA', 'VENDA NOVA', 'VN4'),
      ('PIRINEUS', 'LESTE', 'L3'),
      ('PLANALTO', 'NORTE', 'N3'),
      ('POMPÉIA', 'LESTE', 'L3'),
      ('PONGELUPE', 'BARREIRO', 'B4'),
      ('POUSADA SANTO ANTÔNIO', 'NORDESTE', 'NE2'),
      ('PRADO', 'OESTE', 'O1'),
      ('PRIMEIRO DE MAIO', 'NORTE', 'N4'),
      ('PROVIDÊNCIA', 'NORTE', 'N4'),
      ('RENASCENÇA', 'NORDESTE', 'NE4'),
      ('RIBEIRO DE ABREU', 'NORDESTE', 'NE1'),
      ('RIO BRANCO', 'VENDA NOVA', 'VN3'),
      ('SAGRADA FAMÍLIA', 'LESTE', 'L2'),
      ('SALGADO FILHO', 'OESTE', 'O1'),
      ('SANTA AMÉLIA', 'PAMPULHA', 'P1'),
      ('SANTA BRANCA', 'PAMPULHA', 'P1'),
      ('SANTA CECÍLIA', 'BARREIRO', 'B5'),
      ('SANTA CRUZ', 'NORDESTE', 'NE4'),
      ('SANTA EFIGÊNIA', 'CENTRO-SUL', 'CS1'),
      ('SANTA HELENA', 'BARREIRO', 'B2'),
      ('SANTA INÊS', 'LESTE', 'L1'),
      ('SANTA ISABEL', 'CENTRO-SUL', 'CS3'),
      ('SANTA LÚCIA', 'CENTRO-SUL', 'CS4'),
      ('SANTA MARGARIDA', 'BARREIRO', 'B2'),
      ('SANTA MARIA', 'OESTE', 'O2'),
      ('SANTA MÔNICA', 'VENDA NOVA', 'VN3'),
      ('SANTA RITA', 'BARREIRO', 'B5'),
      ('SANTA RITA DE CÁSSIA', 'CENTRO-SUL', 'CS5'),
      ('SANTA ROSA', 'PAMPULHA', 'P3'),
      ('SANTA SOFIA', 'OESTE', 'O3'),
      ('SANTA TEREZA', 'LESTE', 'L2'),
      ('SANTA TEREZINHA', 'PAMPULHA', 'P4'),
      ('SANTANA DO CAFEZAL', 'CENTRO-SUL', 'CS3'),
      ('SANTO AGOSTINHO', 'CENTRO-SUL', 'CS1'),
      ('SANTO ANDRÉ', 'NOROESTE', 'NO1'),
      ('SANTO ANTÔNIO', 'CENTRO-SUL', 'CS4'),
      ('SATÉLITE', 'NORTE', 'N1'),
      ('SAUDADE', 'LESTE', 'L3'),
      ('SAVASSI', 'CENTRO-SUL', 'CS1'),
      ('SENHOR DOS PASSOS', 'NOROESTE', 'NO1'),
      ('SERRA', 'CENTRO-SUL', 'CS2'),
      ('SERRA DO CURRAL', 'BARREIRO', 'B4'),
      ('SERRA VERDE', 'VENDA NOVA', 'VN1'),
      ('SERRANO', 'PAMPULHA', 'P4'),
      ('SILVEIRA', 'NORDESTE', 'NE5'),
      ('SION', 'CENTRO-SUL', 'CS2'),
      ('SOLAR DO BARREIRO', 'BARREIRO', 'B4'),
      ('SOLIMÕES', 'NORTE', 'N2'),
      ('SPORT CLUB', 'OESTE', 'O2'),
      ('SUMARÉ', 'NOROESTE', 'NO1'),
      ('SUZANA', 'PAMPULHA', 'P3'),
      ('SÃO BENEDITO', 'NORDESTE', 'NE2'),
      ('SÃO BENTO', 'CENTRO-SUL', 'CS4'),
      ('SÃO BERNARDO', 'NORTE', 'N3'),
      ('SÃO CRISTÓVÃO', 'NOROESTE', 'NO1'),
      ('SÃO DAMIÃO', 'VENDA NOVA', 'VN1'),
      ('SÃO FRANCISCO', 'PAMPULHA', 'P3'),
      ('SÃO FRANCISCO DAS CHAGAS', 'NOROESTE', 'NO4'),
      ('SÃO GABRIEL', 'NORDESTE', 'NE1'),
      ('SÃO GERALDO', 'LESTE', 'L1'),
      ('SÃO GONÇALO', 'NORTE', 'N4'),
      ('SÃO JORGE I', 'OESTE', 'O3'),
      ('SÃO JORGE II', 'OESTE', 'O3'),
      ('SÃO JORGE III', 'OESTE', 'O3'),
      ('SÃO JOSÉ', 'PAMPULHA', 'P2'),
      ('SÃO JOÃO', 'BARREIRO', 'B1'),
      ('SÃO JOÃO BATISTA', 'VENDA NOVA', 'VN3'),
      ('SÃO LUCAS', 'CENTRO-SUL', 'CS2'),
      ('SÃO LUÍZ', 'PAMPULHA', 'P2'),
      ('SÃO MARCOS', 'NORDESTE', 'NE3'),
      ('SÃO PAULO', 'NORDESTE', 'NE3'),
      ('SÃO PEDRO', 'CENTRO-SUL', 'CS4'),
      ('SÃO SALVADOR', 'NOROESTE', 'NO3'),
      ('SÃO SEBASTIÃO', 'NORDESTE', 'NE4'),
      ('SÃO TOMÁZ', 'NORTE', 'N3'),
      ('SÃO VICENTE', 'LESTE', 'L2'),
      ('TAQUARIL', 'LESTE', 'L4'),
      ('TEIXEIRA DIAS', 'BARREIRO', 'B2'),
      ('TIRADENTES', 'NORDESTE', 'NE4'),
      ('TIROL', 'BARREIRO', 'B3'),
      ('TREVO', 'PAMPULHA', 'P1'),
      ('TRÊS MARIAS', 'NORDESTE', 'NE1'),
      ('TUPI A', 'NORTE', 'N2'),
      ('TUPI B', 'NORTE', 'N2'),
      ('TÚNEL DE IBIRITÉ', 'BARREIRO', 'B3'),
      ('UNIDAS', 'VENDA NOVA', 'VN4'),
      ('UNIVERSITÁRIO', 'PAMPULHA', 'P3'),
      ('UNIVERSO', 'VENDA NOVA', 'VN4'),
      ('UNIÃO', 'NORDESTE', 'NE5'),
      ('URCA', 'PAMPULHA', 'P4'),
      ('VALE DO JATOBÁ', 'BARREIRO', 'B5'),
      ('VENDA NOVA', 'VENDA NOVA', 'VN3'),
      ('VENTOSA', 'OESTE', 'O4'),
      ('VERA CRUZ', 'LESTE', 'L3'),
      ('VILA AEROPORTO', 'NORTE', 'N3'),
      ('VILA AEROPORTO JARAGUÁ', 'PAMPULHA', 'P3'),
      ('VILA ANTENA', 'OESTE', 'O3'),
      ('VILA ANTENA MONTANHÊS', 'PAMPULHA', 'P4'),
      ('VILA BANDEIRANTES', 'CENTRO-SUL', 'CS5'),
      ('VILA BARRAGEM SANTA LÚCIA', 'CENTRO-SUL', 'CS5'),
      ('VILA BATIK', 'BARREIRO', 'B5'),
      ('VILA BETÂNIA', 'OESTE', 'O4'),
      ('VILA BOA VISTA', 'LESTE', 'L1'),
      ('VILA CALAFATE', 'OESTE', 'O2'),
      ('VILA CALIFÓRNIA', 'NOROESTE', 'NO3'),
      ('VILA CANTO DO SABIÁ', 'VENDA NOVA', 'VN3'),
      ('VILA CEMIG', 'BARREIRO', 'B4'),
      ('VILA CLÓRIS', 'NORTE', 'N3'),
      ('VILA COPACABANA', 'VENDA NOVA', 'VN4'),
      ('VILA COPASA', 'BARREIRO', 'B1'),
      ('VILA COQUEIRAL', 'NOROESTE', 'NO3'),
      ('VILA DA AMIZADE', 'OESTE', 'O2'),
      ('VILA DA LUZ', 'NORDESTE', 'NE2'),
      ('VILA DA PAZ', 'NORDESTE', 'NE4'),
      ('VILA DA ÁREA', 'LESTE', 'L4'),
      ('VILA DAS OLIVEIRAS', 'NOROESTE', 'NO4'),
      ('VILA DE SÁ', 'NORDESTE', 'NE5'),
      ('VILA DIAS', 'LESTE', 'L2'),
      ('VILA DO POMBAL', 'NORDESTE', 'NE4'),
      ('VILA DOS ANJOS', 'VENDA NOVA', 'VN4'),
      ('VILA ECOLÓGICA', 'BARREIRO', 'B5'),
      ('VILA ENGENHO NOGUEIRA', 'PAMPULHA', 'P2'),
      ('VILA ESPLANADA', 'NORDESTE', 'NE1'),
      ('VILA FORMOSA', 'BARREIRO', 'B5'),
      ('VILA FUMEC', 'CENTRO-SUL', 'CS3'),
      ('VILA HAVAÍ', 'OESTE', 'O4'),
      ('VILA INDEPENDÊNCIA I', 'BARREIRO', 'B5'),
      ('VILA INDEPENDÊNCIA II', 'BARREIRO', 'B5'),
      ('VILA INDEPENDÊNCIA IV', 'BARREIRO', 'B5'),
      ('VILA INESTAN', 'NORDESTE', 'NE4'),
      ('VILA IPIRANGA', 'NORDESTE', 'NE5'),
      ('VILA JARDIM ALVORADA', 'PAMPULHA', 'P4'),
      ('VILA JARDIM LEBLON', 'VENDA NOVA', 'VN4'),
      ('VILA JARDIM MONTANHÊS', 'PAMPULHA', 'P4'),
      ('VILA JARDIM SÃO JOSÉ', 'PAMPULHA', 'P4'),
      ('VILA MADRE GERTRUDES I', 'OESTE', 'O2'),
      ('VILA MADRE GERTRUDES II', 'OESTE', 'O2'),
      ('VILA MADRE GERTRUDES III', 'OESTE', 'O2'),
      ('VILA MADRE GERTRUDES V', 'OESTE', 'O2'),
      ('VILA MALOCA', 'NOROESTE', 'NO1'),
      ('VILA MANGUEIRAS', 'BARREIRO', 'B5'),
      ('VILA MANTIQUEIRA', 'VENDA NOVA', 'VN2'),
      ('VILA MARIA', 'NORDESTE', 'NE2'),
      ('VILA MINASLÂNDIA', 'NORTE', 'N4'),
      ('VILA NOSSA SENHORA APARECIDA', 'VENDA NOVA', 'VN3'),
      ('VILA NOSSA SENHORA DO ROSÁRIO', 'LESTE', 'L3'),
      ('VILA NOVA', 'NORTE', 'N1'),
      ('VILA NOVA CACHOEIRINHA I', 'NOROESTE', 'NO1'),
      ('VILA NOVA CACHOEIRINHA II', 'NOROESTE', 'NO1'),
      ('VILA NOVA CACHOEIRINHA IV', 'NORDESTE', 'NE4'),
      ('VILA NOVA DOS MILIONÁRIOS', 'BARREIRO', 'B1'),
      ('VILA NOVA GAMELEIRA I', 'OESTE', 'O2'),
      ('VILA NOVA GAMELEIRA II', 'OESTE', 'O2'),
      ('VILA NOVA GAMELEIRA III', 'OESTE', 'O2'),
      ('VILA NOVA PARAÍSO', 'OESTE', 'O4'),
      ('VILA NOVO SÃO LUCAS', 'CENTRO-SUL', 'CS3'),
      ('VILA OESTE', 'OESTE', 'O2'),
      ('VILA OLHOS D''ÁGUA', 'BARREIRO', 'B1'),
      ('VILA OURO MINAS', 'NORDESTE', 'NE1'),
      ('VILA PAQUETÁ', 'PAMPULHA', 'P2'),
      ('VILA PARAÍSO', 'LESTE', 'L3'),
      ('VILA PARIS', 'CENTRO-SUL', 'CS4'),
      ('VILA PETRÓPOLIS', 'BARREIRO', 'B5'),
      ('VILA PILAR', 'BARREIRO', 'B1'),
      ('VILA PINHO', 'BARREIRO', 'B5'),
      ('VILA PIRATININGA', 'BARREIRO', 'B3'),
      ('VILA PIRATININGA VENDA NOVA', 'VENDA NOVA', 'VN4'),
      ('VILA PRIMEIRO DE MAIO', 'NORTE', 'N4'),
      ('VILA PUC', 'NOROESTE', 'NO4'),
      ('VILA REAL I', 'PAMPULHA', 'P3'),
      ('VILA REAL II', 'PAMPULHA', 'P3'),
      ('VILA RICA', 'PAMPULHA', 'P3'),
      ('VILA SANTA MÔNICA', 'VENDA NOVA', 'VN4'),
      ('VILA SANTA ROSA', 'PAMPULHA', 'P3'),
      ('VILA SANTO ANTÔNIO', 'PAMPULHA', 'P3'),
      ('VILA SANTO ANTÔNIO BARROQUINHA', 'PAMPULHA', 'P4'),
      ('VILA SATÉLITE', 'VENDA NOVA', 'VN1'),
      ('VILA SESC', 'VENDA NOVA', 'VN2'),
      ('VILA SUMARÉ', 'NOROESTE', 'NO1'),
      ('VILA SUZANA I', 'PAMPULHA', 'P3'),
      ('VILA SUZANA II', 'PAMPULHA', 'P3'),
      ('VILA SÃO DIMAS', 'NORDESTE', 'NE1'),
      ('VILA SÃO FRANCISCO', 'PAMPULHA', 'P3'),
      ('VILA SÃO GABRIEL', 'NORDESTE', 'NE1'),
      ('VILA SÃO GABRIEL JACUÍ', 'NORDESTE', 'NE1'),
      ('VILA SÃO GERALDO', 'LESTE', 'L1'),
      ('VILA SÃO JOÃO BATISTA', 'VENDA NOVA', 'VN3'),
      ('VILA SÃO PAULO', 'NORDESTE', 'NE3'),
      ('VILA SÃO RAFAEL', 'LESTE', 'L3'),
      ('VILA TIROL', 'BARREIRO', 'B2'),
      ('VILA TRINTA E UM DE MARÇO', 'NOROESTE', 'NO3'),
      ('VILA UNIÃO', 'LESTE', 'L3'),
      ('VILA VERA CRUZ I', 'LESTE', 'L3'),
      ('VILA VERA CRUZ II', 'LESTE', 'L3'),
      ('VILA VISTA ALEGRE', 'OESTE', 'O2'),
      ('VILA ÁTILA DE PAIVA', 'BARREIRO', 'B2'),
      ('VIRGÍNIA', 'OESTE', 'O2'),
      ('VISTA ALEGRE', 'OESTE', 'O2'),
      ('VISTA DO SOL', 'NORDESTE', 'NE1'),
      ('VITÓRIA', 'NORDESTE', 'NE2'),
      ('VITÓRIA DA CONQUISTA', 'BARREIRO', 'B5'),
      ('VÁRZEA DA PALMA', 'VENDA NOVA', 'VN4'),
      ('XANGRI-LÁ', 'PAMPULHA', 'P1'),
      ('XODÓ-MARIZE', 'NORTE', 'N1'),
      ('ZILAH SPÓSITO', 'NORTE', 'N1'),
      ('ÁGUAS CLARAS', 'BARREIRO', 'B5'),
      ('ÁLVARO CAMARGOS', 'NOROESTE', 'NO3'),
      ('ÁPIA', 'CENTRO-SUL', 'CS5'),
      ('ÁTILA DE PAIVA', 'BARREIRO', 'B2')`,
    );

    await queryRunner.query(
      `CREATE TABLE "bairros_llm_cache" ("id" SERIAL NOT NULL, "valor_bruto_normalizado" text NOT NULL, "bairro_inferido" text, "confianca" double precision, "resolvido" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_bairros_llm_cache_valor_bruto" UNIQUE ("valor_bruto_normalizado"), CONSTRAINT "PK_bairros_llm_cache" PRIMARY KEY ("id"))`,
    );

    await queryRunner.query(
      `ALTER TABLE "avistamentos" ADD "bairro_normalizado" text`,
    );
    await queryRunner.query(`ALTER TABLE "avistamentos" ADD "regional" text`);
    await queryRunner.query(`ALTER TABLE "avistamentos" ADD "territorio" text`);
    await queryRunner.query(
      `ALTER TABLE "avistamentos" ADD "bairro_normalizacao_metodo" text`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "avistamentos" DROP COLUMN "bairro_normalizacao_metodo"`,
    );
    await queryRunner.query(
      `ALTER TABLE "avistamentos" DROP COLUMN "territorio"`,
    );
    await queryRunner.query(
      `ALTER TABLE "avistamentos" DROP COLUMN "regional"`,
    );
    await queryRunner.query(
      `ALTER TABLE "avistamentos" DROP COLUMN "bairro_normalizado"`,
    );
    await queryRunner.query(`DROP TABLE "bairros_llm_cache"`);
    await queryRunner.query(`DROP TABLE "bairros_regionais"`);
  }
}
